### ISSUE TITLE
Blank white pictures when using USGS

### ISSUE THREAD

**Issue by NewoIsTaken** [abassign/Photoscenary#31]
Hey @abassign,

When using `--map 2` (USGS), I get blank images. Here is the full command I am doing: `julia -t $(nproc) photoscenary.jl -s 4 --over 1 -i KBOS -p /home/newo/.fgfs/Scenery/Ortho --map 2`.

**Comment by abassign** [comment]
Hi, sorry if I answer you just now.
I have noticed that the coverage of the USGS is not complete, I think it is due to national security issues, or to format issues that I honestly do not understand. The same problem occurs if you want to see area 51 (KXTA) ... If you use --map 2 you will see a white surface which is equivalent to a surface not visible for censorship reasons. If you put --map 1 instead it works! Obviously for area 51 the censorship makes sense, I honestly don't know what the problem is for KBOS.
If you know if there is an alternate US server that does not have this problem please let me know that I am including it among the usable servers.
I tried with --map 2 for KSFO (San Francisco Int. Airport) everything works perfectly.
I checked with KBOS and wrote the command like this:
With -s 2 (2048 pix)
julia -t 10 photoscenary.jl -i kbos -s 2 --over 2
It works!
With -s 3 (4096 pix)
julia -t 10 photoscenary.jl -i kbos -s 3 --over 2
With -s 4 (8192pix)
julia -t 10 photoscenary.jl -i kbos -s 4 --over 2
It does not work as it gives white images, this means that the USGS server has a resolution limit for certain areas.

**Comment by NewoIsTaken** [comment]
Hey @abassign, yeah, the problem is that USGS only provides images up to 4096x4096. It is listed [here](https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/) at the bottom of the page. Thanks for the reply!
